markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: tzwlwy
author: "tzwlwy"
email: 13758216976@163.com
name: "tzwlwy's blog"
url: https://tzwlwy.github.io/
all_categories: [
["python", "python","/posts/python.html"],
["jmeter", "jmeter","/posts/jmeter.html"],
["flask", "flask","/posts/flask.html"],
["linux", "Linux","/posts/linux.html"],
["performance", "自动化","/posts/performance.html"],
["other", "随笔","/posts/other.html"],
]

paginate: 1
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
