markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: tzwlwy
author: "王焱"
email: 13758216976@163.com
name: "王焱个人博客"
url: https://tzwlwy.github.io/
all_categories: [
["python", "python自动化","/posts/android.html"], 
["program", "jmeter接口","/posts/program.html"],
["web", "jmeter性能","/posts/web.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "CS自动化","/posts/read.html"], 
["other", "其它","/posts/other.html"],
]

paginate: 1
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
